# Copyright 2020 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

exports_files([
    "kotlin-compiler-embeddable-reshade.jarjar",
    "kotlin-compiler-reshade.jarjar",
])

bzl_library(
    name = "jvm",
    srcs = glob(
        ["*.bzl"],
        exclude = ["android.bzl"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:bzl",
        "@bazel_skylib//lib:sets",
        "@bazel_skylib//rules:common_settings",
        "@rules_cc//cc/common",
    ],
)

cc_binary(
    name = "native_java_launcher",
    srcs = ["native_java_launcher.cc"],
    copts = select({
        "@platforms//os:windows": ["/std:c++17"],
        "//conditions:default": ["-std=c++17"],
    }),
    visibility = ["//visibility:public"],
    deps = [":native_java_launcher_lib"],
)

cc_library(
    name = "native_java_launcher_lib",
    hdrs = ["native_java_launcher.h"],
    deps = ["@rules_cc//cc/runfiles"],
)
