/*
 * Copyright 2026 The Bazel Authors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

package io.bazel.kotlin.generate

import com.google.common.truth.Truth.assertThat
import io.bazel.kotlin.generate.GenerateReleaseMetadata.Companion.parseNamedValue
import io.bazel.kotlin.generate.GenerateReleaseMetadata.Companion.sha256Hex
import io.bazel.kotlin.generate.GenerateReleaseMetadata.JarEntry
import io.bazel.kotlin.generate.GenerateReleaseMetadata.ReleaseManifest
import io.bazel.kotlin.generate.GenerateReleaseMetadata.ReleaseNotes
import io.bazel.kotlin.generate.GenerateReleaseMetadata.StatusFile
import io.bazel.kotlin.generate.GenerateReleaseMetadata.UrlTemplates
import org.junit.Assert.assertThrows
import org.junit.Test
import java.nio.file.Files
import java.nio.file.Paths

class GenerateReleaseMetadataTest {
  // The real release-notes template, wired in via `data` + `-Dnotes.template` in BUILD.bazel.
  private val NOTES_TEMPLATE: String =
    Files.readString(Paths.get(System.getProperty("notes.template")))

  @Test
  fun sha256HexMatchesKnownDigest() {
    assertThat(sha256Hex("abc".toByteArray(Charsets.UTF_8)))
      .isEqualTo("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
  }

  @Test
  fun statusFileReadsKeyedLine() {
    assertThat(StatusFile("STABLE_X 1\nVERSION 2.4.20\n").version("VERSION"))
      .isEqualTo("2.4.20")
  }

  @Test
  fun statusFileReturnsDefaultWhenKeyAbsent() {
    assertThrows(IllegalArgumentException::class.java) {
      StatusFile("STABLE_X 1\n").version("VERSION")
    }
  }

  @Test
  fun releaseManifestIsDeterministicAndSorted() {
    val rendered =
      ReleaseManifest(
        "2.4.20",
        mapOf(
          "b" to JarEntry("u2", "s2"),
          "a" to JarEntry("u1", "s1"),
        ),
      ).render()
    assertThat(rendered).contains("VERSION = \"2.4.20\"")
    assertThat(rendered.indexOf("\"a\"")).isLessThan(rendered.indexOf("\"b\""))
    assertThat(rendered).contains("url = \"u1\"")
    assertThat(rendered).contains("sha256 = \"s1\"")
  }

  @Test
  fun releaseManifestRendersValidBzl() {
    val rendered =
      ReleaseManifest(
        "2.4.20",
        mapOf(
          "b" to JarEntry("u2", "s2"),
          "a" to JarEntry("u1", "s1"),
        ),
      ).render()
    // License header and the "generated by" provenance line credit this target.
    assertThat(rendered).startsWith("# Copyright")
    assertThat(rendered).contains("# DO NOT EDIT: generated by bazel build //:release_metadata")
    // Top-level symbols consumed by initialize.release.bzl.
    assertThat(rendered).contains("JARS = {")
    assertThat(rendered).contains("VERSION = \"2.4.20\"")
    assertThat(rendered).contains("\"a\" : struct(")
    assertThat(rendered).contains("url = \"u1\"")
    assertThat(rendered).contains("sha256 = \"s1\"")
  }

  @Test
  fun releaseManifestIsDeterministic() {
    val jars =
      mapOf(
        "b" to JarEntry("u2", "s2"),
        "a" to JarEntry("u1", "s1"),
      )
    assertThat(ReleaseManifest("2.4.20", jars).render())
      .isEqualTo(ReleaseManifest("2.4.20", jars).render())
  }

  @Test
  fun releaseNotesSubstitutesVersionExactly() {
    assertThat(ReleaseNotes(NOTES_TEMPLATE, "2.4.20").render()).isEqualTo(
      "# Release notes for 2.4.20\n" +
        "## Using Bzlmod with Bazel >=7\n" +
        "\n" +
        "1. Enable with `common --enable_bzlmod` in `.bazelrc`.\n" +
        "2. Add to your `MODULE.bazel` file:\n" +
        "\n" +
        "```starlark\n" +
        "bazel_dep(name = \"rules_kotlin\", version = \"2.4.20\")\n" +
        "```\n",
    )
  }

  @Test
  fun releaseNotesLeavesNoPlaceholder() {
    val rendered = ReleaseNotes(NOTES_TEMPLATE, "2.4.20").render()
    assertThat(rendered).contains("bazel_dep(name = \"rules_kotlin\", version = \"2.4.20\")")
    assertThat(rendered).doesNotContain("{version}")
  }

  @Test
  fun urlTemplateResolvesNamedTemplate() {
    assertThat(
      UrlTemplates(mapOf("kotlin" to "https://host/{name}-{version}.jar"))
        .resolve("kotlin", "2.4.20"),
    ).isEqualTo("https://host/kotlin-2.4.20.jar")
  }

  @Test
  fun urlTemplateFallsBackToWildcard() {
    assertThat(
      UrlTemplates(mapOf("*" to "https://host/{name}.jar"))
        .resolve("kotlin", "2.4.20"),
    ).isEqualTo("https://host/kotlin.jar")
  }

  @Test
  fun urlTemplateIsEmptyWhenUnmatched() {
    assertThat(UrlTemplates(emptyMap()).resolve("kotlin", "2.4.20"))
      .isEmpty()
  }

  @Test
  fun namedValueParsesNameEqualsValue() {
    val (name, value) = parseNamedValue("kotlin=/path/to.jar")
    assertThat(name).isEqualTo("kotlin")
    assertThat(value).isEqualTo("/path/to.jar")
  }

  @Test(expected = IllegalArgumentException::class)
  fun namedValueRejectsMissingName() {
    parseNamedValue("=value")
  }
}
