load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary", "kt_jvm_library", "kt_jvm_test")
load(":run_native.bzl", "run_native")

kt_jvm_library(
    name = "native_library",
    srcs = ["Native.kt"],
    runtime_deps = ["@native_dep//:native"],
)

kt_jvm_library(
    name = "exported",
    exports = [":native_library"],
)

kt_jvm_binary(
    name = "native_binary",
    main_class = "Native",
    runtime_deps = [":exported"],
)

kt_jvm_test(
    name = "native_test",
    main_class = "Native",
    test_class = "Native",
    runtime_deps = [":exported"],
)

run_native(
    name = "as_tool",
    tool = ":native_binary",
)

kt_jvm_test(
    name = "launch_test",
    srcs = ["LaunchTest.kt"],
    args = [
        "$(rootpath :native_binary)",
        "$(rootpath :as_tool)",
    ],
    data = [
        ":as_tool",
        ":native_binary",
    ],
    # Encode embedded quotes before passing arguments to the Windows launcher.
    jvm_flags = ["-Djdk.lang.Process.allowAmbiguousCommands=false"],
    main_class = "LaunchTest",
    test_class = "LaunchTest",
)
