load("//src/main/kotlin:bootstrap.bzl", "kt_bootstrap_library")

filegroup(
    name = "all_files",
    srcs = glob(["*"]),
    visibility = ["//:__subpackages__"],
)

kt_bootstrap_library(
    name = "worker",
    srcs = glob(["*.kt"]),
    visibility = [
        "//:__subpackages__",
    ],
    deps = [
        "@bazel_worker_java//:worker_protocol_java_proto",
        "@bazel_worker_java//src/main/java/com/google/devtools/build/lib/worker:work_request_handlers",
        "@com_google_protobuf//:protobuf_java",
        "@com_google_protobuf//:protobuf_java_util",
    ],
)
