load("//src/main/kotlin:bootstrap.bzl", "kt_bootstrap_library")

kt_bootstrap_library(
    name = "worker",
    srcs = glob(["*.kt"]),
    visibility = [
        "//:__subpackages__",
    ],
    deps = [
        "//third_party:protobuf_java",
        "//third_party:protobuf_java_util",
        "//third_party:work_request_handlers",
        "//third_party:worker_protocol_java_proto",
        "@kotlin_rules_maven//:com_google_auto_value_auto_value",
        "@kotlin_rules_maven//:com_google_code_findbugs_jsr305",
        "@kotlin_rules_maven//:com_google_errorprone_error_prone_annotations",
        "@kotlin_rules_maven//:com_google_guava_guava",
    ],
)
