load("//kotlin:jvm.bzl", "kt_jvm_binary", "kt_jvm_import", "kt_jvm_library")
load("//kotlin/compiler:compiler.bzl", _KOTLIN_STDLIBS = "KOTLIN_STDLIBS")

kt_jvm_binary(
    name = "release_metadata",
    main_class = "io.bazel.kotlin.generate.GenerateReleaseMetadata",
    visibility = ["//visibility:public"],
    runtime_deps = [
        ":generate",
    ],
)

# Work around neverlink.
kt_jvm_import(
    name = "kotlinc_jar",
    jars = [
        "@com_github_jetbrains_kotlin//:kotlin-compiler",
    ],
    deps = _KOTLIN_STDLIBS,
)

kt_jvm_library(
    name = "generate",
    srcs = glob(["**/*.kt"]),
    visibility = [
        "//src:__subpackages__",
    ],
    deps = [
        ":kotlinc_jar",
        "//kotlin/compiler:kotlin-reflect",
        "//src/main/kotlin/io/bazel/kotlin/builder/utils",
    ],
)

kt_jvm_binary(
    name = "kotlin_release_options",
    args = [
        "--out",
        "$${BUILD_WORKSPACE_DIRECTORY}/src/main/starlark/core/repositories/kotlin",
    ],
    main_class = "io.bazel.kotlin.generate.WriteKotlincCapabilities",
    runtime_deps = [
        ":generate",
    ],
)
