/*
 * Copyright 2026 The Bazel Authors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

package io.bazel.kotlin.generate

import io.bazel.kotlin.builder.utils.ArgMaps
import io.bazel.kotlin.builder.utils.Flag
import java.nio.file.FileSystems
import java.nio.file.Files
import java.security.MessageDigest

class GenerateReleaseMetadata {
  companion object {
    @JvmStatic
    fun main(args: Array<String>) {
      GenerateReleaseMetadata().generate(args)
    }

    fun parseNamedValue(arg: String): Pair<String, String> {
      val idx = arg.indexOf('=')
      require(idx > 0) { "expected name=value but got '$arg'" }
      return arg.substring(0, idx) to arg.substring(idx + 1)
    }

    fun sha256Hex(bytes: ByteArray): String =
      MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02x".format(it) }

  }

  fun generate(args: Array<String>) {
    val fs = FileSystems.getDefault()
    val argMap = ArgMaps.from(args.toList())

    val version =
      StatusFile(Files.readString(fs.getPath(argMap.mandatorySingle(MetadataArg.VERSION_FILE))))
        .version(argMap.mandatorySingle(MetadataArg.VERSION_KEY))

    val urls = UrlTemplates(namedValues(argMap.optional(MetadataArg.URL)))

    val entries =
      namedValues(argMap.optional(MetadataArg.JAR)).mapValues { (name, path) ->
        JarEntry(
          url = urls.resolve(name, version),
          sha256 = sha256Hex(Files.readAllBytes(fs.getPath(path))),
        )
      }

    Files.writeString(
      fs.getPath(argMap.mandatorySingle(MetadataArg.OUT_BZL)),
      ReleaseManifest(version, entries).render(),
    )

    Files.writeString(
      fs.getPath(argMap.mandatorySingle(MetadataArg.OUT_NOTES)),
      ReleaseNotes(version).render(),
    )
  }

  private fun namedValues(raw: List<String>?): Map<String, String> =
    raw.orEmpty().associate { parseNamedValue(it) }


  data class JarEntry(
    val url: String,
    val sha256: String,
  )

  class StatusFile(
    private val text: String,
  ) {
    fun version(key: String): String =
      requireNotNull(
        text.lineSequence()
        .map(String::trim)
        .filter(String::isNotEmpty)
        .mapNotNull { line -> line.split(' ', limit = 2).takeIf { it.size == 2 } }
        .firstOrNull { it[0] == key }
        ?.let { it[1].trim() }
      ) {"`$text` does not have required $key"}
  }

  class UrlTemplates(
    private val templates: Map<String, String>,
  ) {
    fun resolve(
      name: String,
      version: String,
    ): String =
      (templates[name] ?: templates[WILDCARD] ?: "")
        .replace("{version}", version)
        .replace("{name}", name)

    companion object {
      const val WILDCARD = "*"
    }
  }

  class ReleaseManifest(
    private val version: String,
    private val jars: Map<String, JarEntry>,
  ) {
    fun render(): String {
      val jarEntries =
        jars.keys.sorted().joinToString("\n",prefix="\n", postfix="\n") { name ->
          val entry = jars.getValue(name)
          """    "$name": struct(url = "${entry.url}", sha256 = "${entry.sha256}"),"""
        }
      return """
      |# Generated by GenerateReleaseMetadata. Do not edit.
      |
      |JARS = {$jarEntries}
      |
      |VERSION = "$version"
      |
    """.trimMargin()
    }
  }

  class ReleaseNotes(
    private val version: String,
  ) {
    fun render(): String =
      """
    |# Release notes for $version
    |## Using Bzlmod with Bazel >=7
    |
    |1. Enable with `common --enable_bzlmod` in `.bazelrc`.
    |2. Add to your `MODULE.bazel` file:
    |
    |```starlark
    |bazel_dep(name = "rules_kotlin", version = "$version")
    |```
    |
    """.trimMargin()
  }

  enum class MetadataArg(
    override val flag: String,
  ) : Flag {
    VERSION_FILE("--version_file"),
    VERSION_KEY("--version_key"),
    OUT_BZL("--out_bzl"),
    OUT_NOTES("--out_notes"),
    JAR("--jar"),
    URL("--url"),
  }
}
